# Generated by Django 3.2.13 on 2022-04-20 09:59

from django.db import migrations, models
import predict.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/default.jpg', upload_to=predict.models.image_upload_to)),
            ],
        ),
    ]
